version: "3.8"
services:

  gateway:
    image: nginx:1.19.8-alpine
    ports:
      - 8080:8080
    networks:
      - backend
    volumes:
      - ./Gateway/nginx.conf:/etc/nginx/nginx.conf
      - ./Gateway/api_gateway.conf:/etc/nginx/api_gateway.conf

  user-service:
    image: userservice:compose_build
    build:
      context: ./user-service
      dockerfile: Dockerfile
    networks:
      - backend
    environment:
      PORT: ${USER_SERVICE_PORT}
      MONGODB_URI: "mongodb+srv://draga:draga@cluster0.dlhjqkp.mongodb.net/?retryWrites=true&w=majority"


  apartment-service:
    image: apartmentservice:compose_build
    build:
      context: ./apartment-service
      dockerfile: Dockerfile
    networks:
      - backend
    environment:
      PORT: ${APARTMENT_SERVICE_PORT}
      MONGODB_URI: "mongodb+srv://draga:draga@cluster0.dlhjqkp.mongodb.net/?retryWrites=true&w=majority"


  reservation-service:
    image: reservationservice:compose_build
    build:
      context: ./reservation-service
      dockerfile: Dockerfile
    networks:
      - backend
    environment:
      PORT: ${RESERVATION_SERVICE_PORT}
      MONGODB_URI: "mongodb+srv://draga:draga@cluster0.dlhjqkp.mongodb.net/?retryWrites=true&w=majority"

networks:
  backend:
    name: booking
    driver: bridge
