// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user_reservation_service.proto

package user_reservation

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Reservation struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	GuestId              string   `protobuf:"bytes,2,opt,name=GuestId,proto3" json:"GuestId,omitempty"`
	ApartmentId          string   `protobuf:"bytes,3,opt,name=ApartmentId,proto3" json:"ApartmentId,omitempty"`
	StartDate            string   `protobuf:"bytes,4,opt,name=startDate,proto3" json:"startDate,omitempty"`
	EndDate              string   `protobuf:"bytes,5,opt,name=endDate,proto3" json:"endDate,omitempty"`
	GuestsNumber         int32    `protobuf:"varint,6,opt,name=guestsNumber,proto3" json:"guestsNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Reservation) Reset()         { *m = Reservation{} }
func (m *Reservation) String() string { return proto.CompactTextString(m) }
func (*Reservation) ProtoMessage()    {}
func (*Reservation) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c7aa90bffe879a4, []int{0}
}

func (m *Reservation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Reservation.Unmarshal(m, b)
}
func (m *Reservation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Reservation.Marshal(b, m, deterministic)
}
func (m *Reservation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Reservation.Merge(m, src)
}
func (m *Reservation) XXX_Size() int {
	return xxx_messageInfo_Reservation.Size(m)
}
func (m *Reservation) XXX_DiscardUnknown() {
	xxx_messageInfo_Reservation.DiscardUnknown(m)
}

var xxx_messageInfo_Reservation proto.InternalMessageInfo

func (m *Reservation) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Reservation) GetGuestId() string {
	if m != nil {
		return m.GuestId
	}
	return ""
}

func (m *Reservation) GetApartmentId() string {
	if m != nil {
		return m.ApartmentId
	}
	return ""
}

func (m *Reservation) GetStartDate() string {
	if m != nil {
		return m.StartDate
	}
	return ""
}

func (m *Reservation) GetEndDate() string {
	if m != nil {
		return m.EndDate
	}
	return ""
}

func (m *Reservation) GetGuestsNumber() int32 {
	if m != nil {
		return m.GuestsNumber
	}
	return 0
}

type ListOfReservation struct {
	Reservations         []*Reservation `protobuf:"bytes,1,rep,name=reservations,proto3" json:"reservations,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ListOfReservation) Reset()         { *m = ListOfReservation{} }
func (m *ListOfReservation) String() string { return proto.CompactTextString(m) }
func (*ListOfReservation) ProtoMessage()    {}
func (*ListOfReservation) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c7aa90bffe879a4, []int{1}
}

func (m *ListOfReservation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListOfReservation.Unmarshal(m, b)
}
func (m *ListOfReservation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListOfReservation.Marshal(b, m, deterministic)
}
func (m *ListOfReservation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListOfReservation.Merge(m, src)
}
func (m *ListOfReservation) XXX_Size() int {
	return xxx_messageInfo_ListOfReservation.Size(m)
}
func (m *ListOfReservation) XXX_DiscardUnknown() {
	xxx_messageInfo_ListOfReservation.DiscardUnknown(m)
}

var xxx_messageInfo_ListOfReservation proto.InternalMessageInfo

func (m *ListOfReservation) GetReservations() []*Reservation {
	if m != nil {
		return m.Reservations
	}
	return nil
}

type GetReservationRequest struct {
	GuestId              string   `protobuf:"bytes,1,opt,name=GuestId,proto3" json:"GuestId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetReservationRequest) Reset()         { *m = GetReservationRequest{} }
func (m *GetReservationRequest) String() string { return proto.CompactTextString(m) }
func (*GetReservationRequest) ProtoMessage()    {}
func (*GetReservationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c7aa90bffe879a4, []int{2}
}

func (m *GetReservationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetReservationRequest.Unmarshal(m, b)
}
func (m *GetReservationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetReservationRequest.Marshal(b, m, deterministic)
}
func (m *GetReservationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetReservationRequest.Merge(m, src)
}
func (m *GetReservationRequest) XXX_Size() int {
	return xxx_messageInfo_GetReservationRequest.Size(m)
}
func (m *GetReservationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetReservationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetReservationRequest proto.InternalMessageInfo

func (m *GetReservationRequest) GetGuestId() string {
	if m != nil {
		return m.GuestId
	}
	return ""
}

type GetReservationResponse struct {
	Reservations         *ListOfReservation `protobuf:"bytes,1,opt,name=reservations,proto3" json:"reservations,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *GetReservationResponse) Reset()         { *m = GetReservationResponse{} }
func (m *GetReservationResponse) String() string { return proto.CompactTextString(m) }
func (*GetReservationResponse) ProtoMessage()    {}
func (*GetReservationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c7aa90bffe879a4, []int{3}
}

func (m *GetReservationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetReservationResponse.Unmarshal(m, b)
}
func (m *GetReservationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetReservationResponse.Marshal(b, m, deterministic)
}
func (m *GetReservationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetReservationResponse.Merge(m, src)
}
func (m *GetReservationResponse) XXX_Size() int {
	return xxx_messageInfo_GetReservationResponse.Size(m)
}
func (m *GetReservationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetReservationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetReservationResponse proto.InternalMessageInfo

func (m *GetReservationResponse) GetReservations() *ListOfReservation {
	if m != nil {
		return m.Reservations
	}
	return nil
}

type HiRequest struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HiRequest) Reset()         { *m = HiRequest{} }
func (m *HiRequest) String() string { return proto.CompactTextString(m) }
func (*HiRequest) ProtoMessage()    {}
func (*HiRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c7aa90bffe879a4, []int{4}
}

func (m *HiRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HiRequest.Unmarshal(m, b)
}
func (m *HiRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HiRequest.Marshal(b, m, deterministic)
}
func (m *HiRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HiRequest.Merge(m, src)
}
func (m *HiRequest) XXX_Size() int {
	return xxx_messageInfo_HiRequest.Size(m)
}
func (m *HiRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HiRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HiRequest proto.InternalMessageInfo

func (m *HiRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type HiResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HiResponse) Reset()         { *m = HiResponse{} }
func (m *HiResponse) String() string { return proto.CompactTextString(m) }
func (*HiResponse) ProtoMessage()    {}
func (*HiResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c7aa90bffe879a4, []int{5}
}

func (m *HiResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HiResponse.Unmarshal(m, b)
}
func (m *HiResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HiResponse.Marshal(b, m, deterministic)
}
func (m *HiResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HiResponse.Merge(m, src)
}
func (m *HiResponse) XXX_Size() int {
	return xxx_messageInfo_HiResponse.Size(m)
}
func (m *HiResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HiResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HiResponse proto.InternalMessageInfo

func (m *HiResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*Reservation)(nil), "user_reservation.Reservation")
	proto.RegisterType((*ListOfReservation)(nil), "user_reservation.ListOfReservation")
	proto.RegisterType((*GetReservationRequest)(nil), "user_reservation.GetReservationRequest")
	proto.RegisterType((*GetReservationResponse)(nil), "user_reservation.GetReservationResponse")
	proto.RegisterType((*HiRequest)(nil), "user_reservation.HiRequest")
	proto.RegisterType((*HiResponse)(nil), "user_reservation.HiResponse")
}

func init() {
	proto.RegisterFile("user_reservation_service.proto", fileDescriptor_1c7aa90bffe879a4)
}

var fileDescriptor_1c7aa90bffe879a4 = []byte{
	// 345 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0xd1, 0x4a, 0x02, 0x41,
	0x14, 0x6d, 0x34, 0x0d, 0xef, 0x4a, 0xd4, 0x40, 0x36, 0x98, 0xc5, 0x32, 0x51, 0xed, 0x93, 0x91,
	0x7d, 0x81, 0x12, 0x68, 0x10, 0x05, 0x2b, 0xf5, 0xd0, 0x8b, 0x8c, 0xed, 0x4d, 0xe6, 0xc1, 0x5d,
	0x9b, 0x19, 0x03, 0x3f, 0xac, 0xbf, 0xe8, 0xa3, 0x62, 0xd7, 0xdd, 0x9c, 0xdd, 0x35, 0x7a, 0x9b,
	0x7b, 0xce, 0x3d, 0x73, 0xce, 0xbd, 0x5c, 0x38, 0x5b, 0x6a, 0x54, 0x13, 0x85, 0x1a, 0xd5, 0xa7,
	0x30, 0x32, 0x0a, 0x27, 0xf1, 0x4b, 0xbe, 0x61, 0x77, 0xa1, 0x22, 0x13, 0xd1, 0x83, 0x22, 0xcf,
	0xbf, 0x08, 0x38, 0xfe, 0xa6, 0xa6, 0xfb, 0x50, 0x91, 0x01, 0x23, 0x2e, 0xf1, 0x1a, 0x7e, 0x45,
	0x06, 0x94, 0xc1, 0xde, 0x70, 0x89, 0xda, 0xdc, 0x07, 0xac, 0x92, 0x80, 0x59, 0x49, 0x5d, 0x70,
	0xfa, 0x0b, 0xa1, 0xcc, 0x1c, 0xc3, 0x98, 0xad, 0x26, 0xac, 0x0d, 0xd1, 0x0e, 0x34, 0xb4, 0x11,
	0xca, 0xdc, 0x09, 0x83, 0x6c, 0x37, 0xe1, 0x37, 0x40, 0xfc, 0x33, 0x86, 0x41, 0xc2, 0xd5, 0xd6,
	0x3f, 0xa7, 0x25, 0xe5, 0xd0, 0x9c, 0xc5, 0x26, 0xfa, 0x71, 0x39, 0x9f, 0xa2, 0x62, 0x75, 0x97,
	0x78, 0x35, 0x3f, 0x87, 0xf1, 0x17, 0x38, 0x7c, 0x90, 0xda, 0x3c, 0xbd, 0xdb, 0xe1, 0xfb, 0xd0,
	0xb4, 0x66, 0xd3, 0x8c, 0xb8, 0x55, 0xcf, 0xe9, 0x9d, 0x76, 0x8b, 0x53, 0x77, 0x2d, 0x91, 0x9f,
	0x93, 0xf0, 0x1b, 0x38, 0x1a, 0xa2, 0xb1, 0x79, 0xfc, 0x88, 0x7d, 0xed, 0x45, 0x90, 0xdc, 0x22,
	0xb8, 0x80, 0x56, 0x51, 0xa2, 0x17, 0x51, 0xa8, 0x91, 0x0e, 0x4b, 0x79, 0x88, 0xe7, 0xf4, 0xce,
	0xcb, 0x79, 0x4a, 0xa3, 0x14, 0x52, 0x5d, 0x40, 0x63, 0x24, 0xad, 0x24, 0x73, 0xd4, 0x5a, 0xcc,
	0x30, 0x4b, 0x92, 0x96, 0xfc, 0x12, 0x20, 0x6e, 0x4b, 0xdd, 0xff, 0xec, 0xeb, 0x7d, 0x13, 0x68,
	0x3d, 0x6b, 0x54, 0x96, 0xe1, 0x78, 0x7d, 0x27, 0x74, 0x00, 0xb5, 0xb1, 0x58, 0x8d, 0x24, 0x3d,
	0x29, 0xa7, 0xfc, 0x8d, 0xd0, 0xee, 0x6c, 0x27, 0x53, 0xe3, 0x10, 0x8e, 0xf3, 0x0b, 0x19, 0xac,
	0xb2, 0xa3, 0xb9, 0x2a, 0x0b, 0xb7, 0xae, 0xbb, 0xed, 0xfd, 0xdf, 0xb8, 0x76, 0xe3, 0x3b, 0x03,
	0xf6, 0xda, 0x4a, 0xce, 0xfb, 0xba, 0x28, 0x99, 0xd6, 0x13, 0xfc, 0xf6, 0x27, 0x00, 0x00, 0xff,
	0xff, 0x4d, 0x0f, 0x4c, 0x05, 0x18, 0x03, 0x00, 0x00,
}
